title: Martin Moreno # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo)
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p></p>
  <p align="center">
    <a href=pdf/resume.pdf> Resume </a>
    <a>  |  </a>
    <a href="https://www.linkedin.com/in/martinrmoreno/">LinkedIn</a> 
    <a>  |  </a>
    <a href="https://github.com/martomor">Github</a> 
  </p>
  <p align="justify">
    Certified Data Scientist and MLOPs Engineer. I build, deploy, monitor, iteratively improve, and scale Machine
    Learning Models operating in cloud-based (Azure, AWS and GCP) or On-Prem production environments.
    <br></br>
    Currently working as an Associate Data Scientist in Marsh McLennan
  </p>

theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
